apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}
    database: ${POSTGRES_DB:-taskflow}
    user: ${POSTGRES_USER:-postgres}
    password: ${POSTGRES_PASSWORD:-postgres}
    isDefault: true
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 600
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-postgres}
    editable: true
